apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  namespace: open5gs
  labels:
    app: ueransim-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-gnb
  template:
    metadata:
      labels:
        app: ueransim-gnb
      #annotations:
        #cni.projectcalico.org/ipAddrs: '["10.10.0.131"]'
    spec:
      hostNetwork: true           # TAMBAHKAN BARIS INI
      dnsPolicy: ClusterFirstWithHostNet  # TAMBAHKAN BARIS INI
      containers:
      - name: gnb
        image: ueransim:local
        imagePullPolicy: Never
        command: ["/ueransim/build/nr-gnb"]
        args: ["-c", "/etc/ueransim/gnb.yaml"]
        volumeMounts:
        - name: config
          mountPath: /etc/ueransim
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
      volumes:
      - name: config
        configMap:
          name: ueransim-gnb-config
